# Generated by Django 4.2.6 on 2023-10-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specilization', models.CharField(max_length=150)),
                ('doctorname', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('maritalstatus', models.CharField(max_length=150)),
                ('visittime', models.CharField(max_length=150)),
                ('days', models.CharField(max_length=150)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
