# Generated by Django 4.2.6 on 2023-11-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_patientappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentnumber', models.CharField(max_length=150)),
                ('departmentname', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseasename', models.CharField(max_length=150)),
                ('symptoms', models.CharField(max_length=150)),
                ('doctorname', models.CharField(max_length=150)),
            ],
        ),
    ]
